version: "3"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "80:80"
      - "443:443"
      - "9001:9001"
    volumes:
      - ./stacks:/appsmith-stacks
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  auto_update:
    image: containrrr/watchtower:latest-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update check interval in seconds.
    command: --interval 300 --label-enable --cleanup

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=symfony
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=symfony
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3333:3306"

  symfony:
    image: php:8-fpm
    build:
      context: phpdocker
    volumes:
      - './symfony:/symfony'
      - './phpdocker/xdebug.ini:/usr/local/etc/php/conf.d/20-xdebug.ini'
      - './phpdocker/error_reporting.ini:/usr/local/etc/php/conf.d/10-error_reporting.ini'

  nginx:
    image: nginx:latest
    ports:
      - '8080:8080'
    volumes:
      - './symfony:/symfony'
      - './nginx/site.conf:/etc/nginx/conf.d/site.conf'
